import { Product } from './types';

export const COMMON_PRODUCTS: Product[] = [
  // Mercearia
  { id: '1', name: 'Arroz 5kg', category: 'Mercearia', suggestedPrice: 29.90 },
  { id: '2', name: 'Feijão Carioca 1kg', category: 'Mercearia', suggestedPrice: 8.50 },
  { id: '3', name: 'Feijão Preto 1kg', category: 'Mercearia', suggestedPrice: 9.20 },
  { id: '4', name: 'Açúcar Refinado 1kg', category: 'Mercearia', suggestedPrice: 4.80 },
  { id: '5', name: 'Café em Pó 500g', category: 'Mercearia', suggestedPrice: 18.90 },
  { id: '6', name: 'Óleo de Soja 900ml', category: 'Mercearia', suggestedPrice: 6.50 },
  { id: '7', name: 'Macarrão Espaguete 500g', category: 'Mercearia', suggestedPrice: 3.50 },
  { id: '8', name: 'Molho de Tomate 340g', category: 'Mercearia', suggestedPrice: 2.50 },
  { id: '9', name: 'Sal Refinado 1kg', category: 'Mercearia', suggestedPrice: 2.20 },
  { id: '10', name: 'Farinha de Trigo 1kg', category: 'Mercearia', suggestedPrice: 5.50 },
  { id: '11', name: 'Farinha de Mandioca 500g', category: 'Mercearia', suggestedPrice: 6.90 },
  { id: '12', name: 'Milho de Pipoca 500g', category: 'Mercearia', suggestedPrice: 4.50 },
  { id: '13', name: 'Azeite de Oliva 500ml', category: 'Mercearia', suggestedPrice: 38.90 },
  { id: '14', name: 'Vinagre 750ml', category: 'Mercearia', suggestedPrice: 3.20 },
  { id: '15', name: 'Maionese 500g', category: 'Mercearia', suggestedPrice: 7.90 },
  { id: '16', name: 'Ketchup 400g', category: 'Mercearia', suggestedPrice: 8.50 },
  { id: '17', name: 'Mostarda 200g', category: 'Mercearia', suggestedPrice: 5.50 },
  { id: '18', name: 'Sardinha em Lata', category: 'Mercearia', suggestedPrice: 4.90 },
  { id: '19', name: 'Atum em Lata', category: 'Mercearia', suggestedPrice: 9.80 },
  { id: '20', name: 'Milho em Conserva', category: 'Mercearia', suggestedPrice: 3.50 },
  { id: '21', name: 'Ervilha em Conserva', category: 'Mercearia', suggestedPrice: 3.20 },
  { id: '22', name: 'Creme de Leite 200g', category: 'Mercearia', suggestedPrice: 2.90 },
  { id: '23', name: 'Leite Condensado 395g', category: 'Mercearia', suggestedPrice: 5.90 },
  { id: '24', name: 'Biscoito Recheado', category: 'Mercearia', suggestedPrice: 2.50 },
  { id: '25', name: 'Biscoito Água e Sal', category: 'Mercearia', suggestedPrice: 4.50 },
  { id: '26', name: 'Chocolate em Pó', category: 'Mercearia', suggestedPrice: 12.90 },
  { id: '27', name: 'Leite em Pó 400g', category: 'Mercearia', suggestedPrice: 16.50 },
  
  // Hortifruti
  { id: '28', name: 'Banana Prata (kg)', category: 'Hortifruti', suggestedPrice: 6.90 },
  { id: '29', name: 'Maçã Fuji (kg)', category: 'Hortifruti', suggestedPrice: 12.50 },
  { id: '30', name: 'Laranja Pêra (kg)', category: 'Hortifruti', suggestedPrice: 5.50 },
  { id: '31', name: 'Mamão Papaia (un)', category: 'Hortifruti', suggestedPrice: 8.90 },
  { id: '32', name: 'Limão Taiti (kg)', category: 'Hortifruti', suggestedPrice: 4.50 },
  { id: '33', name: 'Batata Inglesa (kg)', category: 'Hortifruti', suggestedPrice: 7.90 },
  { id: '34', name: 'Cebola (kg)', category: 'Hortifruti', suggestedPrice: 6.50 },
  { id: '35', name: 'Tomate (kg)', category: 'Hortifruti', suggestedPrice: 9.90 },
  { id: '36', name: 'Alho (cabeça)', category: 'Hortifruti', suggestedPrice: 2.50 },
  { id: '37', name: 'Cenoura (kg)', category: 'Hortifruti', suggestedPrice: 5.90 },
  { id: '38', name: 'Alface (pé)', category: 'Hortifruti', suggestedPrice: 3.50 },
  { id: '39', name: 'Cheiro Verde (maço)', category: 'Hortifruti', suggestedPrice: 2.00 },
  { id: '40', name: 'Ovos Brancos (dúzia)', category: 'Hortifruti', suggestedPrice: 12.90 },
  
  // Padaria e Laticínios
  { id: '41', name: 'Pão Francês (kg)', category: 'Padaria', suggestedPrice: 16.90 },
  { id: '42', name: 'Pão de Forma', category: 'Padaria', suggestedPrice: 7.50 },
  { id: '43', name: 'Leite Integral 1L', category: 'Laticínios', suggestedPrice: 5.20 },
  { id: '44', name: 'Manteiga 200g', category: 'Laticínios', suggestedPrice: 12.90 },
  { id: '45', name: 'Margarina 500g', category: 'Laticínios', suggestedPrice: 6.90 },
  { id: '46', name: 'Queijo Mussarela (kg)', category: 'Laticínios', suggestedPrice: 45.00 },
  { id: '47', name: 'Presunto Cozido (kg)', category: 'Laticínios', suggestedPrice: 32.00 },
  { id: '48', name: 'Iogurte Natural 170g', category: 'Laticínios', suggestedPrice: 3.50 },
  { id: '49', name: 'Requeijão Cremoso', category: 'Laticínios', suggestedPrice: 8.90 },
  
  // Açougue
  { id: '50', name: 'Carne Moída (kg)', category: 'Açougue', suggestedPrice: 34.90 },
  { id: '51', name: 'Filé de Frango (kg)', category: 'Açougue', suggestedPrice: 22.90 },
  { id: '52', name: 'Coxa e Sobrecoxa (kg)', category: 'Açougue', suggestedPrice: 14.90 },
  { id: '53', name: 'Bisteca Suína (kg)', category: 'Açougue', suggestedPrice: 19.90 },
  { id: '54', name: 'Linguiça Toscana (kg)', category: 'Açougue', suggestedPrice: 24.90 },
  
  // Bebidas
  { id: '55', name: 'Refrigerante 2L', category: 'Bebidas', suggestedPrice: 9.90 },
  { id: '56', name: 'Suco de Caixinha 1L', category: 'Bebidas', suggestedPrice: 6.50 },
  { id: '57', name: 'Água Mineral 1.5L', category: 'Bebidas', suggestedPrice: 3.50 },
  { id: '58', name: 'Cerveja Lata 350ml', category: 'Bebidas', suggestedPrice: 4.50 },
  
  // Limpeza
  { id: '59', name: 'Detergente Líquido', category: 'Limpeza', suggestedPrice: 2.50 },
  { id: '60', name: 'Sabão em Pó 1kg', category: 'Limpeza', suggestedPrice: 14.90 },
  { id: '61', name: 'Amaciante 2L', category: 'Limpeza', suggestedPrice: 12.90 },
  { id: '62', name: 'Água Sanitária 1L', category: 'Limpeza', suggestedPrice: 4.50 },
  { id: '63', name: 'Desinfetante 500ml', category: 'Limpeza', suggestedPrice: 6.90 },
  { id: '64', name: 'Esponja de Aço', category: 'Limpeza', suggestedPrice: 3.50 },
  { id: '65', name: 'Esponja de Louça', category: 'Limpeza', suggestedPrice: 2.00 },
  { id: '66', name: 'Saco de Lixo 30L', category: 'Limpeza', suggestedPrice: 8.90 },
  { id: '67', name: 'Papel Higiênico (4un)', category: 'Higiene', suggestedPrice: 7.90 },
  { id: '68', name: 'Sabonete 90g', category: 'Higiene', suggestedPrice: 2.50 },
  { id: '69', name: 'Creme Dental 90g', category: 'Higiene', suggestedPrice: 4.90 },
  { id: '70', name: 'Shampoo 350ml', category: 'Higiene', suggestedPrice: 15.90 },
  { id: '71', name: 'Condicionador 350ml', category: 'Higiene', suggestedPrice: 17.90 },
  { id: '72', name: 'Desodorante Spray', category: 'Higiene', suggestedPrice: 14.50 },
  
  // Outros
  { id: '73', name: 'Fubá 500g', category: 'Mercearia', suggestedPrice: 3.90 },
  { id: '74', name: 'Lentilha 500g', category: 'Mercearia', suggestedPrice: 8.50 },
  { id: '75', name: 'Grão de Bico 500g', category: 'Mercearia', suggestedPrice: 12.50 },
  { id: '76', name: 'Azeitona Verde 100g', category: 'Mercearia', suggestedPrice: 5.90 },
  { id: '77', name: 'Gelatina (pó)', category: 'Mercearia', suggestedPrice: 1.50 },
  { id: '78', name: 'Mistura para Bolo', category: 'Mercearia', suggestedPrice: 6.90 },
  { id: '79', name: 'Leite de Coco 200ml', category: 'Mercearia', suggestedPrice: 4.50 },
  { id: '80', name: 'Coco Ralado 100g', category: 'Mercearia', suggestedPrice: 5.50 },
  { id: '81', name: 'Pimenta do Reino', category: 'Mercearia', suggestedPrice: 2.50 },
  { id: '82', name: 'Colorau', category: 'Mercearia', suggestedPrice: 2.50 },
  { id: '83', name: 'Abacaxi (un)', category: 'Hortifruti', suggestedPrice: 8.90 },
  { id: '84', name: 'Manga (kg)', category: 'Hortifruti', suggestedPrice: 7.50 },
  { id: '85', name: 'Melancia (kg)', category: 'Hortifruti', suggestedPrice: 2.50 },
  { id: '86', name: 'Pimentão Verde (kg)', category: 'Hortifruti', suggestedPrice: 9.90 },
  { id: '87', name: 'Beterraba (kg)', category: 'Hortifruti', suggestedPrice: 5.50 },
  { id: '88', name: 'Repolho (un)', category: 'Hortifruti', suggestedPrice: 4.90 },
  { id: '89', name: 'Queijo Prato (kg)', category: 'Laticínios', suggestedPrice: 48.00 },
  { id: '90', name: 'Ricota (un)', category: 'Laticínios', suggestedPrice: 11.90 },
  { id: '91', name: 'Iogurte Grego', category: 'Laticínios', suggestedPrice: 4.90 },
  { id: '92', name: 'Acém Bovino (kg)', category: 'Açougue', suggestedPrice: 29.90 },
  { id: '93', name: 'Alcatra (kg)', category: 'Açougue', suggestedPrice: 42.00 },
  { id: '94', name: 'Patinho (kg)', category: 'Açougue', suggestedPrice: 38.00 },
  { id: '95', name: 'Lombo Suíno (kg)', category: 'Açougue', suggestedPrice: 21.00 },
  { id: '96', name: 'Sabão em Barra (5un)', category: 'Limpeza', suggestedPrice: 10.90 },
  { id: '97', name: 'Álcool Líquido 1L', category: 'Limpeza', suggestedPrice: 7.90 },
  { id: '98', name: 'Fio Dental', category: 'Higiene', suggestedPrice: 9.50 },
  { id: '99', name: 'Hastes Flexíveis', category: 'Higiene', suggestedPrice: 4.50 },
  { id: '100', name: 'Algodão', category: 'Higiene', suggestedPrice: 5.90 },
];